{% set name = "beautifultable" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beautifultable-{{ version }}.tar.gz
  sha256: 040bc987444965678f4ffdfa2f17ac357f1a13e5875b161c9a1899b375319d17

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - wcwidth

test:
  imports:
    - beautifultable
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pri22296/beautifultable
  summary: Print text tables for terminals
  license: MIT
  license_file: LICENSE.txt
  description: |
    This Package provides BeautifulTable class for easily printing
    tabular data in a visually appealing format to a terminal.
  doc_url: http://beautifultable.readthedocs.io/
  dev_url: https://github.com/pri22296/beautifultable

extra:
  recipe-maintainers:
    - beenje
